### PR TITLE
HW2-Rudametkin Viacheslav KI-02

### PR DESCRIPTION
**Pull request by ITVyas**

### CODE REVIEW

**Review by asterindex — CHANGES_REQUESTED** [review]
lock1.acquire()
lock1.release()

must be in try-finally section

**Comment by ITVyas** [comment]
Added try finnaly section

**Review by asterindex — CHANGES_REQUESTED** [review]
def addRand(shirt, pants, times = 1):
	lock1.acquire()
	try:
		for i in range(times):
			shirt.setPrice(shirt.getPrice() + rand.randrange(1, 500)/10)
	finally:
		lock1.release()

	lock2.acquire()
	try:
		for i in range(times):
			pants.setPrice(pants.getPrice() + rand.randrange(1, 500)/10)
	finally:
		lock2.release()
	pass


---
for the second bunch of the threads, it must be done in other sequence

**Comment by ITVyas** [comment]
Added another addRand function (addRandSecondPart), which is reversed and which is passed for second part of threads.

**Comment by asterindex** [comment]
good job

**Pull request merged**
